from typing import Any, Dict, List, Optional
# pyrefly: ignore [missing-import]
from fastapi import APIRouter, HTTPException, status, Depends
# pyrefly: ignore [missing-import]
from pydantic import BaseModel, Field
# pyrefly: ignore [missing-import]
from sqlalchemy.ext.asyncio import AsyncSession 
# pyrefly: ignore [missing-import]
from langchain_community.chat_models import FakeListChatModel

from database.session import get_db
from services.datasets.service import dataset_service
# pyrefly: ignore [missing-import]
from agents.graph import build_agent_graph
from core.config import settings
from services.microsoft.orchestration.local_runtime import local_runtime_service


router = APIRouter()

# Input model schema
class AnalysisRequest(BaseModel):
    dataset_id: str = Field(..., description="The unique identification UUID of the dataset.")
    goal: str = Field(..., description="The analytical goal: Data Quality Audit, EDA, Executive Summary, or Power BI Preparation.")

# Output response schema
class AnalysisResponse(BaseModel):
    dataset_id: str
    goal: str
    workflow_steps: List[str]
    reasoning: str
    confidence: float
    status: str
    planner_result: Optional[Dict[str, Any]] = None
    quality_result: Optional[Dict[str, Any]] = None
    agent_execution_log: Optional[List[Dict[str, Any]]] = None
    
    # Phase 5 Semantic Blackboard additions
    semantic_goal: Optional[Dict[str, Any]] = None
    semantic_dataset: Optional[Dict[str, Any]] = None
    semantic_issues: Optional[List[Dict[str, Any]]] = None
    semantic_recommendations: Optional[List[Dict[str, Any]]] = None
    semantic_relationships: Optional[List[Dict[str, Any]]] = None
    evaluation_result: Optional[Dict[str, Any]] = None
    
    # Phase 6 Statistics & BI Readiness Agent additions
    bi_readiness_result: Optional[Dict[str, Any]] = None
    semantic_statistics: Optional[Dict[str, Any]] = None
    semantic_powerbi_readiness: Optional[Dict[str, Any]] = None
    semantic_business_metrics: Optional[List[Dict[str, Any]]] = None
    semantic_distributions: Optional[List[Dict[str, Any]]] = None
    semantic_aggregation_recommendations: Optional[List[Dict[str, Any]]] = None
    bi_evidence_confidence: Optional[float] = None
    bi_reasoning_confidence: Optional[float] = None
    bi_recommendation_confidence: Optional[float] = None

    # Presentation briefs generated by dynamic language backend
    executive_summary: Optional[str] = None
    certificate_wording: Optional[str] = None
    management_explanation: Optional[str] = None
    markdown_export_wording: Optional[str] = None

    blackboard_version: Optional[int] = None
    blackboard_entity_count: Optional[int] = None
    blackboard_last_updated_by: Optional[str] = None
    blackboard_last_trace_id: Optional[str] = None


class CleaningApproval(BaseModel):
    action_ids: List[str]

def get_fallback_llm():
    """
    Returns a compiled ChatOpenAI instance if keys are configured,
    otherwise returns a FakeListChatModel for safe offline verification.
    """
    if settings.OPENAI_API_KEY:
        try:
            # pyrefly: ignore [missing-import]
            from langchain_openai import ChatOpenAI
            return ChatOpenAI(
                api_key=settings.OPENAI_API_KEY, 
                model=settings.OPENAI_MODEL,
                temperature=0.0
            )
        except Exception:
            pass
    # Safe fallback list for testing/local executions
    return FakeListChatModel(responses=["Planner Complete execution mock responses"])

@router.post("/analyze", response_model=AnalysisResponse)
async def trigger_analysis(
    request: AnalysisRequest,
    db: AsyncSession = Depends(get_db)
):
    """
    Trigger the multi-agent analysis workflow. Instantiates the LangGraph pipeline
    running the Planner and Quality agents, and returns the execution blackboard logs.
    """
    # 1. Fetch dataset from database
    db_dataset = await dataset_service.get_dataset(db, request.dataset_id)
    if not db_dataset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Dataset with ID '{request.dataset_id}' not found."
        )

    # 2. Update goal in database
    await dataset_service.update_dataset_goal(db, request.dataset_id, request.goal)

    # 3. Instantiate LangGraph
    llm = get_fallback_llm()
    graph = build_agent_graph(llm)

    # 4. Invoke graph execution (passes from START -> Planner -> Quality -> Evaluation -> END)
    initial_state = {
        "dataset_path": db_dataset.file_path,
        "goal": request.goal,
        "schema_info": db_dataset.schema_info,
        "dataset_id": db_dataset.id,
        "dataset_metadata": {
            "filename": db_dataset.filename,
            "file_size_bytes": db_dataset.file_size,
            "row_count": db_dataset.row_count,
            "column_count": db_dataset.column_count,
            "detected_type": db_dataset.detected_type
        },
        "dataset_schema": db_dataset.schema_info,
        "dataset_preview": db_dataset.preview_data,
        "profile_summary": db_dataset.profile_summary,
        "messages": [],
        "current_agent": "system",
        "errors": []
    }

    try:
        final_state = await graph.ainvoke(initial_state)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"LangGraph execution pipeline crashed: {str(e)}"
        )

    # 5. Extract results generated by agents from blackboard
    plan_details = final_state.get("analysis_plan") or {}
    
    # 6. Generate presentation summaries via the active dynamic runtime service
    pbi_readiness = final_state.get("semantic_powerbi_readiness") or {}
    score = pbi_readiness.get("readiness_score", 100)
    status = pbi_readiness.get("overall_rating_text", "ENTERPRISE READY")
    recommendations = pbi_readiness.get("business_recommendations", [])
    
    findings = final_state.get("quality_result", {}).get("findings") or []
    critical_count = sum(1 for f in findings if str(f.get("severity")).lower() == "critical")
    warning_count = sum(1 for f in findings if str(f.get("severity")).lower() == "warning")

    # Extract dimension candidate and quality problem types from blackboard state
    dim_candidates = [r.get("column_name") for r in (final_state.get("semantic_aggregation_recommendations") or []) if r.get("recommended_aggregation") == "None"]
    dim_candidate = dim_candidates[0] if dim_candidates else ""
    
    stats = final_state.get("semantic_statistics") or {}
    problems = []
    if stats.get("duplicate_rows", 0) > 0:
        problems.append("duplicate keys")
    elif any("duplicate" in str(f.get("id")).lower() or "duplicate" in str(f.get("name")).lower() for f in findings):
        problems.append("duplicate keys")
        
    if stats.get("total_nulls", 0) > 0:
        problems.append("null values")
    elif any("missing" in str(f.get("id")).lower() or "null" in str(f.get("id")).lower() for f in findings):
        problems.append("null values")
        
    if any("mixed" in str(f.get("id")).lower() for f in findings):
        problems.append("schema normalization")
    elif critical_count > 0 or warning_count > 0:
        problems.append("schema normalization")

    briefs_input = {
        "score": score,
        "status": status,
        "filename": db_dataset.filename,
        "cols": db_dataset.column_count,
        "rows": db_dataset.row_count,
        "critical": critical_count,
        "warnings": warning_count,
        "recommendations": recommendations,
        "dim_candidate": dim_candidate,
        "problems": problems,
        "agent_execution_log": final_state.get("agent_execution_log")
    }
    
    briefs = local_runtime_service.generate_executive_briefs(briefs_input)
    
    return AnalysisResponse(
        dataset_id=db_dataset.id,
        goal=plan_details.get("goal", request.goal),
        workflow_steps=final_state.get("workflow_steps") or [],
        reasoning=final_state.get("planner_reasoning") or "No planning reasoning logged.",
        confidence=final_state.get("planner_confidence") or 0.90,
        status="analysis_completed",
        planner_result=final_state.get("planner_result"),
        quality_result=final_state.get("quality_result"),
        agent_execution_log=final_state.get("agent_execution_log"),
        
        # Phase 5 additions
        semantic_goal=final_state.get("semantic_goal"),
        semantic_dataset=final_state.get("semantic_dataset"),
        semantic_issues=final_state.get("semantic_issues"),
        semantic_recommendations=final_state.get("semantic_recommendations"),
        semantic_relationships=final_state.get("semantic_relationships"),
        evaluation_result=final_state.get("evaluation_result"),
        
        # Phase 6 additions
        bi_readiness_result=final_state.get("bi_readiness_result"),
        semantic_statistics=final_state.get("semantic_statistics"),
        semantic_powerbi_readiness=final_state.get("semantic_powerbi_readiness"),
        semantic_business_metrics=final_state.get("semantic_business_metrics"),
        semantic_distributions=final_state.get("semantic_distributions"),
        semantic_aggregation_recommendations=final_state.get("semantic_aggregation_recommendations"),
        bi_evidence_confidence=final_state.get("bi_evidence_confidence"),
        bi_reasoning_confidence=final_state.get("bi_reasoning_confidence"),
        bi_recommendation_confidence=final_state.get("bi_recommendation_confidence"),

        # Phase 7 additions
        executive_summary=briefs.get("executive_summary"),
        certificate_wording=briefs.get("certificate_wording"),
        management_explanation=briefs.get("management_explanation"),
        markdown_export_wording=briefs.get("markdown_export_wording"),

        blackboard_version=final_state.get("blackboard_version"),
        blackboard_entity_count=final_state.get("blackboard_entity_count"),
        blackboard_last_updated_by=final_state.get("blackboard_last_updated_by"),
        blackboard_last_trace_id=final_state.get("blackboard_last_trace_id")
    )

@router.post("/clean/approve", response_model=Dict[str, Any])
async def approve_cleaning_actions(approval: CleaningApproval):
    """
    Submit human approval flags for dataset modification actions.
    This respects the core safety principle: No automated data edits.
    """
    return {
        "message": "Approved cleaning actions registered successfully.",
        "approved_ids": approval.action_ids,
        "actions_applied": len(approval.action_ids)
    }
