from typing import Any, Dict, List, Optional
from fastapi import APIRouter, HTTPException, status, Depends
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession
from langchain_community.chat_models import FakeListChatModel

from database.session import get_db
from services.datasets.service import dataset_service
from agents.graph import build_agent_graph
from core.config import settings

router = APIRouter()

# Input model schema
class AnalysisRequest(BaseModel):
    dataset_id: str = Field(..., description="The unique identification UUID of the dataset.")
    goal: str = Field(..., description="The analytical goal: Data Quality Audit, EDA, Executive Summary, or Power BI Preparation.")

# Output response schema
class AnalysisResponse(BaseModel):
    dataset_id: str
    goal: str
    workflow_steps: List[str]
    reasoning: str
    confidence: float
    status: str

class CleaningApproval(BaseModel):
    action_ids: List[str]

def get_fallback_llm():
    """
    Returns a compiled ChatOpenAI instance if keys are configured,
    otherwise returns a FakeListChatModel for safe offline verification.
    """
    if settings.OPENAI_API_KEY:
        try:
            from langchain_openai import ChatOpenAI
            return ChatOpenAI(
                api_key=settings.OPENAI_API_KEY, 
                model=settings.OPENAI_MODEL,
                temperature=0.0
            )
        except Exception:
            pass
    # Safe fallback list for testing/local executions
    return FakeListChatModel(responses=["Planner Complete execution mock responses"])

@router.post("/analyze", response_model=AnalysisResponse)
async def trigger_analysis(
    request: AnalysisRequest,
    db: AsyncSession = Depends(get_db)
):
    """
    Trigger the Planner workflow. Instantiates the LangGraph pipeline,
    extracts the profile summary and executes the Planner Agent reasoning node.
    """
    # 1. Fetch dataset from database
    db_dataset = await dataset_service.get_dataset(db, request.dataset_id)
    if not db_dataset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Dataset with ID '{request.dataset_id}' not found."
        )

    # 2. Update goal in database
    await dataset_service.update_dataset_goal(db, request.dataset_id, request.goal)

    # 3. Instantiate LangGraph
    llm = get_fallback_llm()
    graph = build_agent_graph(llm)

    # 4. Invoke graph execution (passes from START -> Planner -> END)
    initial_state = {
        "dataset_path": db_dataset.file_path,
        "goal": request.goal,
        "schema_info": db_dataset.schema_info,
        "dataset_id": db_dataset.id,
        "dataset_metadata": {
            "filename": db_dataset.filename,
            "file_size_bytes": db_dataset.file_size,
            "row_count": db_dataset.row_count,
            "column_count": db_dataset.column_count,
            "detected_type": db_dataset.detected_type
        },
        "dataset_schema": db_dataset.schema_info,
        "dataset_preview": db_dataset.preview_data,
        "profile_summary": db_dataset.profile_summary,
        "messages": [],
        "current_agent": "system",
        "errors": []
    }

    try:
        final_state = await graph.ainvoke(initial_state)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"LangGraph execution pipeline crashed: {str(e)}"
        )

    # 5. Extract results generated by PlannerAgent
    plan_details = final_state.get("analysis_plan") or {}
    
    return AnalysisResponse(
        dataset_id=db_dataset.id,
        goal=plan_details.get("goal", request.goal),
        workflow_steps=final_state.get("workflow_steps") or [],
        reasoning=final_state.get("planner_reasoning") or "No planning reasoning logged.",
        confidence=final_state.get("planner_confidence") or 0.90,
        status="planning_completed"
    )

@router.post("/clean/approve", response_model=Dict[str, Any])
async def approve_cleaning_actions(approval: CleaningApproval):
    """
    Submit human approval flags for dataset modification actions.
    This respects the core safety principle: No automated data edits.
    """
    return {
        "message": "Approved cleaning actions registered successfully.",
        "approved_ids": approval.action_ids,
        "actions_applied": len(approval.action_ids)
    }
